
# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/uhans/A101/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/blu/r1_plus/propietary/bin/6620_launcher:system/bin/6620_launcher \
	vendor/blu/r1_plus/propietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
	vendor/blu/r1_plus/propietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
	vendor/blu/r1_plus/propietary/bin/aal:system/bin/aal \
	vendor/blu/r1_plus/propietary/bin/AcdApiDaemon:system/bin/AcdApiDaemon \
	vendor/blu/r1_plus/propietary/bin/aee:system/bin/aee \
	vendor/blu/r1_plus/propietary/bin/aee_archive:system/bin/aee_archive \
	vendor/blu/r1_plus/propietary/bin/aee_core_forwarder:system/bin/aee_core_forwarder \
	vendor/blu/r1_plus/propietary/bin/aee_dumpstate:system/bin/aee_dumpstate \
	vendor/blu/r1_plus/propietary/bin/akmd09911:system/bin/akmd09911 \
	vendor/blu/r1_plus/propietary/bin/akmd8963:system/bin/akmd8963 \
	vendor/blu/r1_plus/propietary/bin/akmd8975:system/bin/akmd8975 \
	vendor/blu/r1_plus/propietary/bin/am:system/bin/am \
	vendor/blu/r1_plus/propietary/bin/ami304d:system/bin/ami304d \
	vendor/blu/r1_plus/propietary/bin/applypatch:system/bin/applypatch \
	vendor/blu/r1_plus/propietary/bin/applysig:system/bin/applysig \
	vendor/blu/r1_plus/propietary/bin/appops:system/bin/appops \
	vendor/blu/r1_plus/propietary/bin/app_process32:system/bin/app_process32 \
	vendor/blu/r1_plus/propietary/bin/appwidget:system/bin/appwidget \
	vendor/blu/r1_plus/propietary/bin/atcid:system/bin/atcid \
	vendor/blu/r1_plus/propietary/bin/atci_service:system/bin/atci_service \
	vendor/blu/r1_plus/propietary/bin/atrace:system/bin/atrace \
	vendor/blu/r1_plus/propietary/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
	vendor/blu/r1_plus/propietary/bin/autobt:system/bin/autobt \
	vendor/blu/r1_plus/propietary/bin/autokd:system/bin/autokd \
	vendor/blu/r1_plus/propietary/bin/badblocks:system/bin/badblocks \
	vendor/blu/r1_plus/propietary/bin/batterywarning:system/bin/batterywarning \
	vendor/blu/r1_plus/propietary/bin/bcc:system/bin/bcc \
	vendor/blu/r1_plus/propietary/bin/blkid:system/bin/blkid \
	vendor/blu/r1_plus/propietary/bin/bmgr:system/bin/bmgr \
	vendor/blu/r1_plus/propietary/bin/bmm050d:system/bin/bmm050d \
	vendor/blu/r1_plus/propietary/bin/bootanimation:system/bin/bootanimation \
	vendor/blu/r1_plus/propietary/bin/boot_logo_updater:system/bin/boot_logo_updater \
	vendor/blu/r1_plus/propietary/bin/bu:system/bin/bu \
	vendor/blu/r1_plus/propietary/bin/bugreport:system/bin/bugreport \
	vendor/blu/r1_plus/propietary/bin/ccci_fsd:system/bin/ccci_fsd \
	vendor/blu/r1_plus/propietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
	vendor/blu/r1_plus/propietary/bin/clatd:system/bin/clatd \
	vendor/blu/r1_plus/propietary/bin/content:system/bin/content \
	vendor/blu/r1_plus/propietary/bin/dalvikvm32:system/bin/dalvikvm32 \
	vendor/blu/r1_plus/propietary/bin/debuggerd:system/bin/debuggerd \
	vendor/blu/r1_plus/propietary/bin/dex2oat:system/bin/dex2oat \
	vendor/blu/r1_plus/propietary/bin/dhcp6c:system/bin/dhcp6c \
	vendor/blu/r1_plus/propietary/bin/dhcp6ctl:system/bin/dhcp6ctl \
	vendor/blu/r1_plus/propietary/bin/dhcp6s:system/bin/dhcp6s \
	vendor/blu/r1_plus/propietary/bin/dhcpcd:system/bin/dhcpcd \
	vendor/blu/r1_plus/propietary/bin/dm_agent_binder:system/bin/dm_agent_binder \
	vendor/blu/r1_plus/propietary/bin/dmlog:system/bin/dmlog \
	vendor/blu/r1_plus/propietary/bin/dnsmasq:system/bin/dnsmasq \
	vendor/blu/r1_plus/propietary/bin/downloader:system/bin/downloader \
	vendor/blu/r1_plus/propietary/bin/dpm:system/bin/dpm \
	vendor/blu/r1_plus/propietary/bin/drmserver:system/bin/drmserver \
	vendor/blu/r1_plus/propietary/bin/dumpstate:system/bin/dumpstate \
	vendor/blu/r1_plus/propietary/bin/dumpsys:system/bin/dumpsys \
	vendor/blu/r1_plus/propietary/bin/e2fsck:system/bin/e2fsck \
	vendor/blu/r1_plus/propietary/bin/em_svr:system/bin/em_svr \
	vendor/blu/r1_plus/propietary/bin/epdg_wod:system/bin/epdg_wod \
	vendor/blu/r1_plus/propietary/bin/factory:system/bin/factory \
	vendor/blu/r1_plus/propietary/bin/fsck.f2fs:system/bin/fsck.f2fs \
	vendor/blu/r1_plus/propietary/bin/fsck_msdos:system/bin/fsck_msdos \
	vendor/blu/r1_plus/propietary/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
	vendor/blu/r1_plus/propietary/bin/fuelgauged:system/bin/fuelgauged \
	vendor/blu/r1_plus/propietary/bin/gas_srv:system/bin/gas_srv \
	vendor/blu/r1_plus/propietary/bin/gatekeeperd:system/bin/gatekeeperd \
	vendor/blu/r1_plus/propietary/bin/ged_srv:system/bin/ged_srv \
	vendor/blu/r1_plus/propietary/bin/geomagneticd:system/bin/geomagneticd \
	vendor/blu/r1_plus/propietary/bin/grep:system/bin/grep \
	vendor/blu/r1_plus/propietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
	vendor/blu/r1_plus/propietary/bin/gsm0710muxdmd2:system/bin/gsm0710muxdmd2 \
	vendor/blu/r1_plus/propietary/bin/guiext-server:system/bin/guiext-server \
	vendor/blu/r1_plus/propietary/bin/gzip:system/bin/gzip \
	vendor/blu/r1_plus/propietary/bin/gzip_static:system/bin/gzip_static \
	vendor/blu/r1_plus/propietary/bin/hid:system/bin/hid \
	vendor/blu/r1_plus/propietary/bin/hostapd:system/bin/hostapd \
	vendor/blu/r1_plus/propietary/bin/hostapd_cli:system/bin/hostapd_cli \
	vendor/blu/r1_plus/propietary/bin/idmap:system/bin/idmap \
	vendor/blu/r1_plus/propietary/bin/ime:system/bin/ime \
	vendor/blu/r1_plus/propietary/bin/input:system/bin/input \
	vendor/blu/r1_plus/propietary/bin/installd:system/bin/installd \
	vendor/blu/r1_plus/propietary/bin/install-recovery.sh:system/bin/install-recovery.sh \
	vendor/blu/r1_plus/propietary/bin/ip:system/bin/ip \
	vendor/blu/r1_plus/propietary/bin/ip6tables:system/bin/ip6tables \
	vendor/blu/r1_plus/propietary/bin/ipod:system/bin/ipod \
	vendor/blu/r1_plus/propietary/bin/iptables:system/bin/iptables \
	vendor/blu/r1_plus/propietary/bin/keystore:system/bin/keystore \
	vendor/blu/r1_plus/propietary/bin/kpoc_charger:system/bin/kpoc_charger \
	vendor/blu/r1_plus/propietary/bin/lcdc_screen_cap:system/bin/lcdc_screen_cap \
	vendor/blu/r1_plus/propietary/bin/ld.mc:system/bin/ld.mc \
	vendor/blu/r1_plus/propietary/bin/linker:system/bin/linker \
	vendor/blu/r1_plus/propietary/bin/lmkd:system/bin/lmkd \
	vendor/blu/r1_plus/propietary/bin/logcat:system/bin/logcat \
	vendor/blu/r1_plus/propietary/bin/logd:system/bin/logd \
	vendor/blu/r1_plus/propietary/bin/logwrapper:system/bin/logwrapper \
	vendor/blu/r1_plus/propietary/bin/lsm303md:system/bin/lsm303md \
	vendor/blu/r1_plus/propietary/bin/magd:system/bin/magd \
	vendor/blu/r1_plus/propietary/bin/make_ext4fs:system/bin/make_ext4fs \
	vendor/blu/r1_plus/propietary/bin/make_f2fs:system/bin/make_f2fs \
	vendor/blu/r1_plus/propietary/bin/MATest:system/bin/MATest \
	vendor/blu/r1_plus/propietary/bin/matv:system/bin/matv \
	vendor/blu/r1_plus/propietary/bin/mc6420d:system/bin/mc6420d \
	vendor/blu/r1_plus/propietary/bin/md_ctrl:system/bin/md_ctrl \
	vendor/blu/r1_plus/propietary/bin/mdnsd:system/bin/mdnsd \
	vendor/blu/r1_plus/propietary/bin/media:system/bin/media \
	vendor/blu/r1_plus/propietary/bin/mediaserver:/system/bin/mediaserver \
	vendor/blu/r1_plus/propietary/bin/memorydumper:system/bin/memorydumper \
	vendor/blu/r1_plus/propietary/bin/memsicd:system/bin/memsicd \
	vendor/blu/r1_plus/propietary/bin/memsicd3416x:system/bin/memsicd3416x \
	vendor/blu/r1_plus/propietary/bin/meta_tst:system/bin/meta_tst \
	vendor/blu/r1_plus/propietary/bin/mke2fs:system/bin/mke2fs \
	vendor/blu/r1_plus/propietary/bin/mmp:system/bin/mmp \
	vendor/blu/r1_plus/propietary/bin/monkey:system/bin/monkey \
	vendor/blu/r1_plus/propietary/bin/msensord:system/bin/msensord \
	vendor/blu/r1_plus/propietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
	vendor/blu/r1_plus/propietary/bin/MtkCodecService:system/bin/MtkCodecService \
	vendor/blu/r1_plus/propietary/bin/mtkmal:system/bin/mtkmal \
	vendor/blu/r1_plus/propietary/bin/mtkrild:system/bin/mtkrild \
	vendor/blu/r1_plus/propietary/bin/mtkrildmd2:system/bin/mtkrildmd2 \
	vendor/blu/r1_plus/propietary/bin/mtpd:system/bin/mtpd \
	vendor/blu/r1_plus/propietary/bin/muxreport:system/bin/muxreport \
	vendor/blu/r1_plus/propietary/bin/ndc:system/bin/ndc \
	vendor/blu/r1_plus/propietary/bin/netd:system/bin/netd \
	vendor/blu/r1_plus/propietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
	vendor/blu/r1_plus/propietary/bin/nvram_daemon:system/bin/nvram_daemon \
	vendor/blu/r1_plus/propietary/bin/oatdump:system/bin/oatdump \
	vendor/blu/r1_plus/propietary/bin/orientationd:system/bin/orientationd \
	vendor/blu/r1_plus/propietary/bin/patchoat:system/bin/patchoat
	vendor/blu/r1_plus/propietary/bin/perf_native_test:system/bin/perf_native_test \
	vendor/blu/r1_plus/propietary/bin/ping:system/bin/ping \
	vendor/blu/r1_plus/propietary/bin/ping6:system/bin/ping6 \
	vendor/blu/r1_plus/propietary/bin/pm:system/bin/pm \
	vendor/blu/r1_plus/propietary/bin/ppl_agent:system/bin/ppl_agent \
	vendor/blu/r1_plus/propietary/bin/pppd:system/bin/pppd \
	vendor/blu/r1_plus/propietary/bin/pppd_dt:system/bin/pppd_dt \
	vendor/blu/r1_plus/propietary/bin/pq:system/bin/pq \
	vendor/blu/r1_plus/propietary/bin/program_binary_service:system/bin/program_binary_service \
	vendor/blu/r1_plus/propietary/bin/racoon:system/bin/racoon \
	vendor/blu/r1_plus/propietary/bin/radvd:system/bin/radvd \
	vendor/blu/r1_plus/propietary/bin/reboot:system/bin/reboot \
	vendor/blu/r1_plus/propietary/bin/requestsync:system/bin/requestsync \
	vendor/blu/r1_plus/propietary/bin/resize2fs:system/bin/resize2fs \
	vendor/blu/r1_plus/propietary/bin/resize_ext4:system/bin/resize_ext4 \
	vendor/blu/r1_plus/propietary/bin/rs2spir:system/bin/rs2spir \
	vendor/blu/r1_plus/propietary/bin/rtt:system/bin/rtt \
	vendor/blu/r1_plus/propietary/bin/run-as:system/bin/run-as \
	vendor/blu/r1_plus/propietary/bin/s62xd:system/bin/s62xd \
	vendor/blu/r1_plus/propietary/bin/schedtest:system/bin/schedtest \
	vendor/blu/r1_plus/propietary/bin/screencap:system/bin/screencap \
	vendor/blu/r1_plus/propietary/bin/screenrecord:system/bin/screenrecord \
	vendor/blu/r1_plus/propietary/bin/sdcard:system/bin/sdcard \
	vendor/blu/r1_plus/propietary/bin/sensorservice:system/bin/sensorservice \
	vendor/blu/r1_plus/propietary/bin/service:system/bin/service \
	vendor/blu/r1_plus/propietary/bin/servicemanager:system/bin/servicemanager \
	vendor/blu/r1_plus/propietary/bin/settings:system/bin/settings \
	vendor/blu/r1_plus/propietary/bin/sgdisk:system/bin/sgdisk \
	vendor/blu/r1_plus/propietary/bin/sh:system/bin/sh \
	vendor/blu/r1_plus/propietary/bin/sink:system/bin/sink \
	vendor/blu/r1_plus/propietary/bin/slpd:system/bin/slpd \
	vendor/blu/r1_plus/propietary/bin/sm:system/bin/sm \
	vendor/blu/r1_plus/propietary/bin/sn:system/bin/sn \
	vendor/blu/r1_plus/propietary/bin/source:system/bin/source \
	vendor/blu/r1_plus/propietary/bin/spir2cl:system/bin/spir2cl \
	vendor/blu/r1_plus/propietary/bin/spm_loader:system/bin/spm_loader \
	vendor/blu/r1_plus/propietary/bin/stp_dump3:system/bin/stp_dump3 \
	vendor/blu/r1_plus/propietary/bin/superumount:system/bin/superumount \
	vendor/blu/r1_plus/propietary/bin/surfaceflinger:system/bin/surfaceflinger \
	vendor/blu/r1_plus/propietary/bin/svc:system/bin/svc \
	vendor/blu/r1_plus/propietary/bin/tc:system/bin/tc \
	vendor/blu/r1_plus/propietary/bin/telecom:system/bin/telecom \
	vendor/blu/r1_plus/propietary/bin/terservice:system/bin/terservice \
	vendor/blu/r1_plus/propietary/bin/tertestclient:system/bin/tertestclient \
	vendor/blu/r1_plus/propietary/bin/thermal:system/bin/thermal \
	vendor/blu/r1_plus/propietary/bin/thermald:system/bin/thermald \
	vendor/blu/r1_plus/propietary/bin/thermal_manager:system/bin/thermal_manager \
	vendor/blu/r1_plus/propietary/bin/tiny_mkswap:system/bin/tiny_mkswap \
	vendor/blu/r1_plus/propietary/bin/tiny_swapoff:system/bin/tiny_swapoff \
	vendor/blu/r1_plus/propietary/bin/tiny_swapon:system/bin/tiny_swapon \
	vendor/blu/r1_plus/propietary/bin/toolbox:system/bin/toolbox \
	vendor/blu/r1_plus/propietary/bin/toybox:system/bin/toybox \
	vendor/blu/r1_plus/propietary/bin/tune2fs:system/bin/tune2fs \
	vendor/blu/r1_plus/propietary/bin/tzdatacheck:system/bin/tzdatacheck \
	vendor/blu/r1_plus/propietary/bin/uiautomator:system/bin/uiautomator \
	vendor/blu/r1_plus/propietary/bin/uncrypt:system/bin/uncrypt \
	vendor/blu/r1_plus/propietary/bin/vdc:system/bin/vdc \
	vendor/blu/r1_plus/propietary/bin/vold:system/bin/vold \
	vendor/blu/r1_plus/propietary/bin/volte_imcb:system/bin/volte_imcb \
	vendor/blu/r1_plus/propietary/bin/volte_stack:system/bin/volte_stack \
	vendor/blu/r1_plus/propietary/bin/volte_ua:system/bin/volte_ua \
	vendor/blu/r1_plus/propietary/bin/vtservice:system/bin/vtservice \
	vendor/blu/r1_plus/propietary/bin/wifi2agps:system/bin/wifi2agps \
	vendor/blu/r1_plus/propietary/bin/wm:system/bin/wm \
	vendor/blu/r1_plus/propietary/bin/wmt_loader:system/bin/wmt_loader \
	vendor/blu/r1_plus/propietary/bin/wpa_cli:system/bin/wpa_cli \
	vendor/blu/r1_plus/propietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
	vendor/blu/r1_plus/propietary/bin/xlog:system/bin/xlog \
	vendor/blu/r1_plus/propietary/ect
	vendor/blu/r1_plus/propietary/lib
	vendor/blu/r1_plus/propietary/usr
	vendor/blu/r1_plus/propietary/vendor
	vendor/blu/r1_plus/propietary/xbin
	
	